steam_web_api:
  endpoint: "https://store.steampowered.com/api/appdetails/"

currency_ex_api:
  endpoint: "https://openexchangerates.org/api/latest.json"
  app_token: 'YOUR_OPEN_EXCHANGE_RATES_KEY'

s3_bucket:
  endpoint_url: 'https://nyc3.digitaloceanspaces.com'
  region_name: 'nyc3'
  bucket_name: 'YOUR_BUCKETS_NAME'
  aws_access_key_id: 'AWS_ACCESS_KEY_ID'
  aws_secret_access_key: 'AWS_SECRET_ACCESS_KEY'

steam_prices_etl:
  source:
    src_videogames_list_link: ""
    src_videogame_usd_prices_link: ""
    base_currency: "USD"
    ex_currencies:
      "ar": "ARS"
      "tr": "TRY"
      "ru": "RUB"
      "br": "BRL"
      "ua": "UAH"
      "no": "NOK"
      "cn": "CNY"
      "co": "COP"
      "kz": "KZT"
      "za": "ZAR"
      "mx": "MXN"
      "in": "INR"
      "uy": "UYU"
      "cl": "CLP"
    videogames_appids: [298110,552520,2369390,1245620,1238840,1091500,2138330,2239550,1174180,1811260,1547000,1546990,1546970,12210]
  target:
    trg_filename_available_tags: ""
    trg_filename_usd_ex_rates: ""

logging:
  version: 1
  formatters:
    main_etl:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: main_etl
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]