resources_etl:
  chrome:
    args: ["--disable-popup-blocking", "--headless", "--no-sandbox"]
    kwargs: 
      use_subprocess: true,
      driver_executable_path: "",
      version_main: 121
  
  source:
    src_videogames_list_link: "",
    src_videogame_usd_prices_link: ""

  target:
    trg_filename_available_tags: ""
    trg_filename_usd_ex_rates: ""

logging:
  version: 1
  formatters:
    main_etl:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: main_etl
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]